### ISSUE TITLE
build in arm64??

### ISSUE THREAD

**Issue by emptytaboo** [seemoo-lab/bcm-rpi3#10]
I want to build in 4.8.y arm64?? How can i do ??It support in future?? 
Thx!!

**Comment by E3V3A** [comment]
Currently RPi3 kernels are all 32bit and there is no direct plan to up this to 64bit, since the performance advantages does not make up for the added development needed for this support. At least according to various developer sources.

**Comment by DanielAW** [comment]
Closed for now due to missing kernel support.
