### ISSUE TITLE
Problem with raspberry pi 3 module B

### ISSUE THREAD

**Issue by cnrat** [seemoo-lab/bcm-rpi3#13]
Boot with latest Nexmon https://github.com/seemoo-lab/bcm-rpi3/releases/download/0.3/nexmon_rpi_12-10-2016.tar.gz

Then following the instruction:
`insmod /root/brcmfmac.ko`
`ifconfig wlan0 up`

Then enable airbase-ng and airmon-ng:
`airmon-ng check kill`
`airmon-ng start wlan0`

It show error:

> Interface       Chipset         Driver
> wlan0           Unknown         brcmfmac_sdio - [phy0]mon0: ERROR while getting interface flags: No such device
>(monitor mode enabled on mon0)

Any one can help?

**Comment by XePeleato** [comment]
You don't have to run airmon-ng, after loading the module, the card is set into monitor mode automatically.

**Comment by cnrat** [comment]
Thank you!
