### ISSUE TITLE
how to write dd to sdcard on windows ??(Win32DiskImager)

### ISSUE THREAD

**Issue by Jarvis785** [seemoo-lab/bcm-rpi3#19]
copy the image to your SD card, e.g.: dd if=nexmon_rpi_12-10-2016.dd of=/dev/mmcblk0 bs=1M note: the sd card device (in this example mmcblk0) may change depending on your setup

how windows users will write nexmon_rpi_12-10-2016.dd  to sccard ??
@z

**Comment by matthiasseemoo** [comment]
by becoming a linux or mac user ;-)

Am 29.10.2016 7:39 nachm. schrieb "Warish Kumar Sahoo" <
notifications@github.com>:

**Comment by Jarvis785** [comment]
okey if thats the only way......

**Comment by DanielAW** [comment]
As you already try the [diskmanager](https://sourceforge.net/projects/win32diskimager/)? I thought we got another one which successfully used this tool.

**Comment by Jarvis785** [comment]
what do u mean ??

**Comment by DanielAW** [comment]
"win32diskimager" is more or less a subsitute for "dd" on Windows

**Comment by Jarvis785** [comment]
actually win32 disk imager saying out of space (8gb card)

**Comment by DanielAW** [comment]
closed, same problem as in #20
