### ISSUE TITLE
may i compile the patch on mac?

### ISSUE THREAD

**Issue by uncat** [seemoo-lab/bcm-rpi3#21]
when i try the step `make` it shows that 
`/plugin/include/system.h:481:10: fatal error:
      'malloc.h' file not found'. `
do you know how to fix that?
 (btw,forgive my broken english)

**Comment by matthiasseemoo** [comment]
Use the following repo. it supports mac. but you will either need to
install gcc5 with mac ports or you need to adjust the makefiles on your own.

https://github.com/seemoo-lab/nexmon

Am 03.11.2016 2:37 vorm. schrieb "锦喵" <notifications@github.com>:

**Comment by uncat** [comment]
Thanks~ i bought a very cheap wireless adapter at last( 360 wifi 2nd   
general ），which is compatible to kali on raspberry pi 3

发自我的 iPhone
