### ISSUE TITLE
Doesn't seem to be working with latest raspbian

### ISSUE THREAD

**Issue by BradHuber** [seemoo-lab/bcm-rpi3#24]
Make error likely due to path issues (and more?).

brcmfmac wants /lib/modules/4.4.21-v7+ whereas the latest version is /lib/modules/4.4.32-v7+

how to fix?

**Comment by XePeleato** [comment]
@BradHuber Could you please run `uname -r` and paste the output here?

**Comment by BradHuber** [comment]
uname -r gives:
4.4.32-v7+

**Comment by BradHuber** [comment]
I used the latest raspbian image (4.4.21) without doing apt-get upgrade.  With this version I am able to get the firmware patch compiled and installed.  I won't worry about getting it working with the latest version for now.

Follow-on question- after installation iw-config shows that wlan0 is in monitor mode.  However within wireshark/tshark I cannot use the -I option on the commandline or via the GUI.  So am I still capturing in monitor mode?  When I start capture on wlan0 I do see packets, but I cannot get wireshark to filter on wlan.fc.type == 0 etc...

Any thoughts?

**Comment by michaelcalve** [comment]
In Wireshark, are you talking about enabling monitor mode for the wlan connection?

**Comment by BradHuber** [comment]
Well... yes.  But let me be more specific.

I am trying to use the Raspberry Pi to sniff WiFi probe requests.  Initially I am trying to use wireshark/tshark to do it.

Whether or not wireshark sets the adapter into monitor mode or if it is already in monitor mode doesn't matter to me.

iwconfig reports that the device is in monitor mode.. yet I can't seem to sniff the probe requests (none appear in wireshark).

**Comment by BradHuber** [comment]
And yes I am talking about the wlan0 adapter on the ras-pi

**Comment by BradHuber** [comment]
It's the built in wlan interface on the raspbery pi 3

**Comment by michaelcalve** [comment]
Hmmm. Im actually trying to do the same thing since wireshark cant enable
monitoring on my pi

**Comment by DanielAW** [comment]
@BradHuber You should be able to use Wireshark without using the `-I` option. The Wifi interface is _always_ in monitor mode if you use our patched driver. Apart from the driver it is also essential to replace the original firmware in `/lib/firmware/brcm`. Does tcpdump work? (e.g.: `tcpdump -i wlan0 -s0`)

**Comment by DanielAW** [comment]
Closed for now, no new infos.
