### ISSUE TITLE
Latest version raspbian 4.4.34-v7+ built ok. But can only work in mon mode

### ISSUE THREAD

**Issue by xixixihaha** [seemoo-lab/bcm-rpi3#26]
I built the ko file and patched firmware by following the instruction in Steps to create your own firmware patches - Using your Raspberry Pi
The ko and firmware bin file generated successfully. But after using the new module, it can´t connect to the current SSID. But the mon mode is working. It is strange. 
After moving back the original files, the wireless client mode is recovered.

**Comment by DanielAW** [comment]
Our modified driver does _only_ support monitor mode. If you need station mode you need to switch back to the original driver. Therefore, this is sort of the intended behaviour.
Support for both monitor mode and station mode would require further changes to the driver. This is not our main goal at the moment.
