### ISSUE TITLE
Can't ssh into raspberry

### ISSUE THREAD

**Issue by kushagra12** [seemoo-lab/bcm-rpi3#27]
Hi,
I wanted to try the dd image but because I don't have an monitor, I could only access my RPi via ssh. When I tried ssh, it gave me 'connection refused' error. Is there any way to turn on the ssh?

**Comment by DanielAW** [comment]
Hi,
our image is configured the same way the default Raspbian image is. I personally use the JTAG pins, see http://elinux.org/RPi_Serial_Connection

**Comment by kushagra12** [comment]
Thanks for reply but the serial port to USB will be difficult to get where I live. Raspbian allowed ssh till November release after which we have to place a blank file named ssh in the boot directory to enable it. If you can update your dd image with the November release, I am sure I can enable ssh via same means.

**Comment by DanielAW** [comment]
Closed for now due to migration to https://github.com/seemoo-lab/nexmon
