### ISSUE TITLE
Airmon-ng start wont work

### ISSUE THREAD

**Issue by jokle** [seemoo-lab/bcm-rpi3#28]
After installing the prepared sd card and trying to put wlan0 to monitro mode with command airmon-ng start wlan0 it responds with "ERROR while getting interface flags: no such device". And iwconfig says that mode is managed.

**Comment by DanielAW** [comment]
It is _not_ necessary to call `airmon-ng start wlan0`. Using our driver puts the device automatically in monitor mode. Also: our driver is then uncapable of using Station Mode, you have to switch back to the original driver + firmware to use Station Mode again.
