### ISSUE TITLE
Bluetooth Monitoring either onboard or with a dongle

### ISSUE THREAD

**Issue by michaelcalve** [seemoo-lab/bcm-rpi3#31]
I'm having an issue connecting to the Adafruit bluetooth USB dongle.

Upon bootup there is a [FAILED] Failed to start Configure Bluetooth Modems connected by UART.  See 'systemctl status hciuart.service' for details.

I'm curious if by modifying some of these files, I'll be able to activate the onboard bluetooth and/or the USB.

Mike

**Comment by fblgit** [comment]
i have the same issue, the entire bluetooth system is not working...

**Comment by DanielAW** [comment]
I opend a new ticket for this on the new repository, see: https://github.com/seemoo-lab/nexmon/issues/19
