### ISSUE TITLE
airodump-ng captures corrupted .cap file 

### ISSUE THREAD

**Issue by codeinstein** [seemoo-lab/bcm-rpi3#33]
Hello,
When I try to capture a handshake file with 
airodump-ng --bssid 00:00:00:00:00 -c 6 -w psk wlan0
It works and get the .cap file.
But when I try to do a dictionary attack on the .cap the following error appears:
-invalid packet capture length: corrupted file

Another thing is "fixed missing channel -1" error is appearing on the airodump-ng, this may be causing the issue too.

I also tried cracking the .cap file captured by pi 3 with aircrack-ng on a pc running kali, same error.

Tried most possible solutions but it seems the device doesn't capture a valid handshake file.

I am using Nexmon image.

Is there a fix for this?
Thanks.

**Comment by DanielAW** [comment]
@codeinstein do you use the image provided in this repository? If this is the case please try building NexMon out of this repository https://github.com/seemoo-lab/nexmon based on a current Raspbian. This repository is deprecated from now on.

If the problem still exist then, please reopen a issue on the new repository.
